# Generated by Django 4.0.4 on 2022-05-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
